sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=229b7ac46677b47fb39e8caeeff4ac4e374b0f34663bc4344e3a10fc8ca87205

language: node_js

notifications:
  email: false

node_js: '9'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
